gems: [jekyll-paginate]

permalink: :title

title: azatris
tagline: ♥
url: http://azatris.github.io
paginate: 10
paginate_path: "page:num"
baseurl: ""

encoding: "utf-8"
highlighter: rouge
# markdown: redcarpet 
# redcarpet: 
#   extensions: ["strikethrough"] 

# About
author:
  name: azatris
  email: azatris@gmail.com