gems: [jekyll-paginate]

permalink: :title

title: azatris
tagline: <3
url: http://azatris.github.io/
paginate: 1
paginate_path: "page:num"
baseurl: "http://azatris.github.io/"

encoding: "utf-8"
highlighter: rouge
# markdown: redcarpet 
# redcarpet: 
#   extensions: ["strikethrough"] 

# About
author:
  name: azatris
  email: azatris@gmail.com