plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

permalink: :title

title: Azatris' Belief Box
tagline: ♥
description: Beliefs I hold about the world
url: https://azatris.github.io
paginate: 10
paginate_path: "page:num"
baseurl: ""

encoding: "utf-8"
highlighter: rouge
# markdown: redcarpet 
# redcarpet: 
#   extensions: ["strikethrough"] 

# About
author:
  name: azatris
  email: azatris@gmail.com

twitter:
  username: azatris
  card: summary

logo: /public/apple-touch-icon.png

social:
  name: Silver Taza
  links:
    - https://www.facebook.com/azatris
    - https://twitter.com/azatris
    - https://www.linkedin.com/in/silvertaza
    - https://github.com/azatris

lang: en_US